/**
 * AI_PROJECT_CONTEXT.md generator
 */

import type { AnalysisResult } from '../types/index.js';
import { detectProjectType, generateFolderStructureString } from '../analyzers/file-tree.js';
import { getProjectDescription } from '../analyzers/config-parser.js';

/**
 * Generate AI_PROJECT_CONTEXT.md content
 */
export function generateContextMarkdown(analysis: AnalysisResult): string {
  const timestamp = new Date().toISOString().split('T')[0];
  const projectType = detectProjectType(analysis.projectRoot);
  const description = getProjectDescription(analysis.projectRoot);

  let markdown = `# AI Project Context

> Auto-generated by dotllm. DO NOT EDIT MANUALLY.
> Last updated: ${timestamp}

This document provides essential context for AI assistants to understand this codebase.
Use this as your source of truth for architecture decisions and constraints.

---

## Project Overview

**Name:** ${analysis.projectName}
**Type:** ${projectType}
`;

  if (description) {
    markdown += `**Description:** ${description}\n`;
  }

  // Languages and frameworks
  if (analysis.languages.length > 0) {
    markdown += `**Primary Languages:** ${analysis.languages.join(', ')}\n`;
  }
  if (analysis.frameworks.length > 0) {
    markdown += `**Frameworks:** ${analysis.frameworks.join(', ')}\n`;
  }
  if (analysis.packageManagers.length > 0) {
    markdown += `**Package Manager:** ${analysis.packageManagers.join(', ')}\n`;
  }
  if (analysis.isMonorepo) {
    markdown += `**Architecture:** Monorepo`;
    if (analysis.workspaces && analysis.workspaces.length > 0) {
      markdown += ` (${analysis.workspaces.length} workspaces)`;
    }
    markdown += '\n';
  }

  markdown += '\n---\n\n';

  // Repository structure
  markdown += `## Repository Structure

\`\`\`
${generateFolderStructureString(analysis.folderStructure, '', 3)}\`\`\`

`;

  // Folder responsibilities
  if (analysis.folderResponsibilities.length > 0) {
    markdown += `---

## Folder Responsibilities

| Path | Responsibility | Ownership |
|------|----------------|-----------|
`;
    for (const folder of analysis.folderResponsibilities.slice(0, 20)) {
      const ownership = folder.ownership || '—';
      markdown += `| \`${folder.path}\` | ${folder.responsibility} | ${ownership} |\n`;
    }
    markdown += '\n';
  }

  // Key dependencies
  const keyDeps = analysis.dependencies.filter((d) => !d.isDev).slice(0, 15);
  if (keyDeps.length > 0) {
    markdown += `---

## Key Dependencies

| Package | Version | Purpose |
|---------|---------|---------|
`;
    for (const dep of keyDeps) {
      const purpose = inferDependencyPurpose(dep.name);
      markdown += `| \`${dep.name}\` | ${dep.version} | ${purpose} |\n`;
    }
    markdown += '\n';
  }

  // Critical paths
  if (analysis.criticalPaths.length > 0) {
    markdown += `---

## Critical Paths (Handle with Care)

> [!CAUTION]
> These areas have significant blast radius. Changes require extra review.

| Path | Risk | Reason |
|------|------|--------|
`;
    for (const cp of analysis.criticalPaths) {
      markdown += `| \`${cp.path}\` | ${cp.risk} | ${cp.reason} |\n`;
    }
    markdown += '\n';
  }

  // Infrastructure
  if (analysis.infraTools.length > 0 || analysis.hasDocker || analysis.hasCICD) {
    markdown += `---

## Infrastructure & Deployment

`;
    if (analysis.infraTools.length > 0) {
      markdown += `**Infrastructure Tools:** ${analysis.infraTools.join(', ')}\n`;
    }
    if (analysis.hasDocker) {
      markdown += `**Containerization:** Docker\n`;
    }
    if (analysis.hasCICD) {
      markdown += `**CI/CD:** Configured (check \`.github/workflows\` or equivalent)\n`;
    }
    markdown += '\n';
  }

  // Development info
  markdown += `---

## Development

`;

  // Try to infer common scripts
  const scripts = inferDevelopmentScripts(analysis);
  if (scripts.length > 0) {
    markdown += `### Common Commands

\`\`\`bash
${scripts.join('\n')}
\`\`\`

`;
  }

  // Testing info
  if (analysis.hasTests) {
    markdown += `### Testing

- Test frameworks: ${analysis.testFrameworks.length > 0 ? analysis.testFrameworks.join(', ') : 'Detected'}
- Run tests with the appropriate command for your framework

`;
  }

  // What not to change
  markdown += `---

## What NOT to Change Casually

These areas require careful consideration and potentially team coordination:

`;

  const warnings = getChangeWarnings(analysis);
  for (const warning of warnings) {
    markdown += `1. **${warning.area}** - ${warning.reason}\n`;
  }

  // Footer
  markdown += `
---

## About This Document

This file was generated by [\`dotllm\`](https://www.npmjs.com/package/dotllm) to provide AI assistants with project-specific context.

To regenerate, run:
\`\`\`bash
npx dotllm
\`\`\`
`;

  return markdown;
}

/**
 * Infer the purpose of a dependency based on its name
 */
function inferDependencyPurpose(name: string): string {
  const purposes: Record<string, string> = {
    // React ecosystem
    react: 'UI library',
    'react-dom': 'React DOM renderer',
    next: 'Full-stack React framework',
    remix: 'Full-stack React framework',
    gatsby: 'Static site generator',

    // Vue ecosystem
    vue: 'UI framework',
    nuxt: 'Vue meta-framework',

    // State management
    zustand: 'State management',
    redux: 'State management',
    '@reduxjs/toolkit': 'State management',
    jotai: 'Atomic state management',
    recoil: 'State management',
    mobx: 'State management',
    pinia: 'Vue state management',

    // Data fetching
    '@tanstack/react-query': 'Server state management',
    'react-query': 'Server state management',
    swr: 'Data fetching',
    axios: 'HTTP client',

    // UI frameworks
    '@radix-ui': 'Headless UI primitives',
    '@headlessui': 'Headless UI components',
    '@shadcn': 'UI components',
    tailwindcss: 'CSS framework',
    '@mui/material': 'Material UI components',
    antd: 'UI component library',
    'chakra-ui': 'UI component library',

    // Forms
    'react-hook-form': 'Form handling',
    formik: 'Form handling',
    zod: 'Schema validation',
    yup: 'Schema validation',

    // Backend
    express: 'HTTP server',
    fastify: 'HTTP server',
    hono: 'Edge-first HTTP server',
    '@nestjs/core': 'Backend framework',

    // Database
    prisma: 'Database ORM',
    '@prisma/client': 'Database client',
    'drizzle-orm': 'Database ORM',
    typeorm: 'Database ORM',
    mongoose: 'MongoDB ODM',
    pg: 'PostgreSQL client',

    // Auth
    'next-auth': 'Authentication',
    '@auth/core': 'Authentication',
    passport: 'Authentication middleware',

    // Testing
    jest: 'Testing framework',
    vitest: 'Testing framework',
    '@playwright/test': 'E2E testing',
    cypress: 'E2E testing',

    // Python
    fastapi: 'API framework',
    django: 'Web framework',
    flask: 'Web framework',
    sqlalchemy: 'Database ORM',
    pydantic: 'Data validation',
  };

  // Check for exact match
  if (purposes[name]) return purposes[name];

  // Check for partial matches
  for (const [key, purpose] of Object.entries(purposes)) {
    if (name.includes(key)) return purpose;
  }

  return '—';
}

/**
 * Infer development scripts based on detected tools
 */
function inferDevelopmentScripts(analysis: AnalysisResult): string[] {
  const scripts: string[] = [];

  // Package manager based commands
  const pm = analysis.packageManagers[0];
  if (['npm', 'yarn', 'pnpm', 'bun'].includes(pm)) {
    const run = pm === 'npm' ? 'npm run' : pm;
    scripts.push(`# Install dependencies`);
    scripts.push(`${pm} install`);
    scripts.push('');
    scripts.push(`# Start development server`);
    scripts.push(`${run} dev`);

    if (analysis.hasTests) {
      scripts.push('');
      scripts.push(`# Run tests`);
      scripts.push(`${run} test`);
    }

    if (analysis.lintTools.length > 0) {
      scripts.push('');
      scripts.push(`# Lint code`);
      scripts.push(`${run} lint`);
    }
  } else if (pm === 'pip' || pm === 'poetry' || pm === 'pipenv') {
    scripts.push(`# Install dependencies`);
    if (pm === 'poetry') {
      scripts.push('poetry install');
    } else if (pm === 'pipenv') {
      scripts.push('pipenv install');
    } else {
      scripts.push('pip install -r requirements.txt');
    }
  } else if (pm === 'cargo') {
    scripts.push('# Build project');
    scripts.push('cargo build');
    scripts.push('');
    scripts.push('# Run project');
    scripts.push('cargo run');
  } else if (pm === 'go') {
    scripts.push('# Build project');
    scripts.push('go build');
    scripts.push('');
    scripts.push('# Run project');
    scripts.push('go run .');
  }

  return scripts;
}

/**
 * Get warnings about what not to change casually
 */
function getChangeWarnings(analysis: AnalysisResult): Array<{ area: string; reason: string }> {
  const warnings: Array<{ area: string; reason: string }> = [];

  // Always include auth warning if detected
  if (analysis.criticalPaths.some((cp) => cp.path.includes('auth'))) {
    warnings.push({
      area: 'Authentication flow',
      reason: 'Security critical - changes can expose vulnerabilities',
    });
  }

  // Database migrations
  if (analysis.criticalPaths.some((cp) => cp.path.includes('migration'))) {
    warnings.push({
      area: 'Database migrations',
      reason: 'Schema changes affect production data - coordinate with team',
    });
  }

  // Prisma schema
  if (analysis.databases.includes('prisma')) {
    warnings.push({
      area: 'Prisma schema',
      reason: 'Database schema changes require migrations and can break existing data',
    });
  }

  // Shared types in monorepo
  if (analysis.isMonorepo) {
    warnings.push({
      area: 'Shared packages/types',
      reason: 'Changes affect multiple apps in the monorepo',
    });
  }

  // Infrastructure
  if (analysis.hasInfraAsCode) {
    warnings.push({
      area: 'Infrastructure code (Terraform, etc.)',
      reason: 'Changes can affect production cloud resources',
    });
  }

  // CI/CD
  if (analysis.hasCICD) {
    warnings.push({
      area: 'CI/CD workflows',
      reason: 'Broken workflows can block deployments',
    });
  }

  // Package.json in libraries
  if (analysis.dependencies.length > 0) {
    warnings.push({
      area: 'Dependency versions',
      reason: 'Version changes can introduce breaking changes or vulnerabilities',
    });
  }

  return warnings;
}
