/**
 * AI_CODING_RULES.md generator
 */

import type { AnalysisResult } from '../types/index.js';
import type { RuleSection } from '../types/rules.js';
import { getApplicableRules, countRules } from '../rules/index.js';

/**
 * Generate AI_CODING_RULES.md content
 */
export function generateRulesMarkdown(analysis: AnalysisResult): string {
  const sections = getApplicableRules(analysis);
  const totalRules = countRules(sections);
  const timestamp = new Date().toISOString().split('T')[0];

  let markdown = `# AI Coding Rules

> Auto-generated by dotai. DO NOT EDIT MANUALLY.
> Last updated: ${timestamp}
> Total rules: ${totalRules}

This document defines strict coding rules for AI assistants working in this codebase.
Follow these rules exactly. Do not deviate without explicit user permission.

---

## Detected Stack

`;

  // Add detected stack summary
  if (analysis.languages.length > 0) {
    markdown += `- **Languages:** ${analysis.languages.join(', ')}\n`;
  }
  if (analysis.frameworks.length > 0) {
    markdown += `- **Frameworks:** ${analysis.frameworks.join(', ')}\n`;
  }
  if (analysis.packageManagers.length > 0) {
    markdown += `- **Package Managers:** ${analysis.packageManagers.join(', ')}\n`;
  }
  if (analysis.buildTools.length > 0) {
    markdown += `- **Build Tools:** ${analysis.buildTools.join(', ')}\n`;
  }
  if (analysis.testFrameworks.length > 0) {
    markdown += `- **Testing:** ${analysis.testFrameworks.join(', ')}\n`;
  }
  if (analysis.lintTools.length > 0) {
    markdown += `- **Linting:** ${analysis.lintTools.join(', ')}\n`;
  }
  if (analysis.databases.length > 0) {
    markdown += `- **Databases:** ${analysis.databases.join(', ')}\n`;
  }

  markdown += '\n---\n\n';

  // Add each rule section
  for (const section of sections) {
    markdown += formatRuleSection(section);
  }

  // Add footer
  markdown += `---

## About This Document

This file was generated by [\`dotai\`](https://www.npmjs.com/package/dotai) to provide AI assistants with project-specific coding guidelines.

To regenerate, run:
\`\`\`bash
npx dotai
\`\`\`
`;

  return markdown;
}

/**
 * Format a single rule section
 */
function formatRuleSection(section: RuleSection): string {
  let markdown = `## ${section.title}\n\n`;

  if (section.description) {
    markdown += `${section.description}\n\n`;
  }

  // Standard rules
  for (const rule of section.rules) {
    markdown += `- ${rule.text}\n`;
  }

  // Anti-patterns (DO NOT rules)
  if (section.antiPatterns && section.antiPatterns.length > 0) {
    markdown += `\n### DO NOT\n\n`;
    for (const rule of section.antiPatterns) {
      markdown += `- ❌ ${rule.text}\n`;
    }
  }

  markdown += '\n---\n\n';

  return markdown;
}

/**
 * Get the number of rules that would be generated
 */
export function getRuleCount(analysis: AnalysisResult): number {
  const sections = getApplicableRules(analysis);
  return countRules(sections);
}
